name: vllm-cuda121
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - "setuptools<81"
  - cmake
  - ninja
  - git

  - pip:
      - packaging
      - sortedcontainers
      - pandas
      - sentence-transformers
      - datasets
      - "transformers==4.48.2"
      - "tokenizers==0.21.4"
      - "numpy==1.26.4"
      - matplotlib
